services:
  - type: web
    name: hackblr-dizitalalien
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PORT
        value: 10000
      - key: VITE_VAPI_PUBLIC_KEY
        sync: false
      - key: VITE_VAPI_ASSISTANT_ID
        sync: false
      - key: PYTHON_API_URL
        sync: false
